# 覆盖主题的默认配置
projects_url: http://github.com/esahcorp
nav:
  home: /
  about: /about/
  articles: /archives/
  category: /categories/
  search: /search/
social_links:
  github: http://github.com/esahcorp
  mail: mailto:lostkite@outlook.com
tags_overview: true
highlight: rainbow
disqus:
  enabled: true
  shortname: loskiet
gravatar:
  email: lostkite@outlook.com
  hash: 1b0e23f6bd58528b318d61e2e77d3577